### ISSUE TITLE
3.1 - Class Specific Packages

### ISSUE THREAD

**Issue by AFauxPas** [isaactpetersen/Fantasy-Football-Analytics-Textbook#1]
Were you wanting to have the psych packages loaded in doing the fantasy football analysis?

**Comment by isaactpetersen** [comment]
Thanks for your question! Are you asking whether one should load the `psych` package in the "Load Packages" section of the "Getting Started" chapter?: https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/blob/main/getting-started.qmd#L47

Eventually, yes. I haven't added code yet that uses the `psych` package, but I plan to. I'm only having users load the packages they'd need to run the code on a particular page. Does that answer your question? Let me know if there'd be something that would be helpful to clarify either here or in the code.

Thanks!

**Comment by AFauxPas** [comment]
No, I think that answers it. I saw the instruction for loading that
package, but didn't see it referenced yet in Chapter 3. Sorry for jumping
the gun!

**Comment by isaactpetersen** [comment]
No worries! I will close this issue for now, but feel free to re-post if it would be helpful to re-open. Thanks for your question and engagement!
